using System.Numerics;
using OliveGameStudio;

namespace BattleForce2249;

/// <summary>
/// The overlay the play area is framed with: clear across the middle of the window and closing to
/// dark at the corners.
/// </summary>
/// <remarks>
/// <para>
/// It is drawn over everything else, which is what makes it a frame rather than another thing in
/// the scene — the ship and the debris it is flying through pass beneath it, so what the frame
/// darkens is the edge of the <em>window</em> and not the edge of the world.
/// </para>
/// <para>
/// <b>It intercepts nothing.</b> A sprite is a drawing instruction and this type answers nothing
/// but <see cref="IRenderable.Render"/>, so there is no seam through which the overlay could take
/// a press, a click or a finger from whatever is under it. That is the requirement met by
/// construction rather than by hit-testing the overlay out of the way.
/// </para>
/// <para>
/// <b>The shape is in the asset and how much of it shows is here.</b> The ramp is a smooth
/// gradient with nothing an artist would draw in it — it is generated by
/// <c>scripts/make-vignette.py</c>, which is where the radii are written down — so the tuning
/// worth having in code is how heavily it is laid on, which is <see cref="Strength"/>.
/// </para>
/// </remarks>
public sealed class Vignette : IRenderable
{
    /// <summary>
    /// The asset key the frame is drawn from. An identifier, not text: it is never translated.
    /// </summary>
    public const string AssetKey = "vignette";

    /// <summary>
    /// How much of the frame shows unless something says otherwise, from 0 — no frame at all — to
    /// 1, the mask as it was authored.
    /// </summary>
    /// <remarks>
    /// Untuned, and said plainly: nobody has yet seen this on a screen, and how heavy a frame
    /// should be is a judgement made by looking. Short of the full mask so that the corners are
    /// shaded rather than closed, which is the difference between framing the play area and
    /// cropping it.
    /// </remarks>
    public const float DefaultStrength = 0.75f;

    ITexture? _texture;

    /// <summary>
    /// Gets how much of the frame shows. See <see cref="DefaultStrength"/>.
    /// </summary>
    public float Strength { get; init; } = DefaultStrength;

    /// <inheritdoc />
    /// <remarks>
    /// The texture is loaded on the first frame this draws rather than up front: the graphics
    /// device it belongs to does not exist when the container is built.
    /// </remarks>
    public void Render(IRenderer renderer)
    {
        Vector2 viewport = renderer.ViewportSize;

        // Nothing is framed on a window of no size, and stretching a texture across one is a
        // division that means nothing. Asked as "is this drawable" rather than as an ordered
        // comparison against zero, because every ordered comparison against NaN is false: written
        // the other way round, the one value this exists to stop is the one value it lets through.
        // This is the same guard the star field states, for the same reason.
        if (!IsDrawableExtent(viewport.X) || !IsDrawableExtent(viewport.Y))
        {
            return;
        }

        ITexture texture = _texture ??= renderer.Textures.Load(AssetKey);

        renderer.Draw(new Sprite(
            Texture: texture,
            // The middle of the window, placed by the middle of the mask, so the clear part of the
            // frame sits over the part of the screen the ship is held in.
            Position: viewport / 2f,
            Rotation: 0f,
            Origin: new Vector2(texture.Width, texture.Height) / 2f,
            Scale: 1f)
        {
            // The whole size is carried here rather than split between a scale and a stretch. The
            // mask is authored square and a window is not, so there is no uniform part to factor
            // out: what this says is "one texture, exactly this window", on both axes.
            Stretch = new Vector2(viewport.X / texture.Width, viewport.Y / texture.Height),
            Colour = Colour.White.WithAlpha(Strength),
        });
    }

    /// <summary>
    /// Whether a measurement is one the frame can be stretched across: a finite extent, above zero.
    /// </summary>
    static bool IsDrawableExtent(float value) => float.IsFinite(value) && value > 0f;
}
