<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <MonoGamePlatform>Desktop</MonoGamePlatform>
        <RootNamespace>BattleForce2249</RootNamespace>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5"/>
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\src\BattleForce2249\BattleForce2249.csproj" />
      <ProjectReference Include="..\src\OliveGameStudio.Abstractions\OliveGameStudio.Abstractions.csproj" />
      <ProjectReference Include="..\src\OliveGameStudio.UI.Abstractions\OliveGameStudio.UI.Abstractions.csproj" />
      <ProjectReference Include="..\src\OliveGameStudio.UI\OliveGameStudio.UI.csproj" />
      <ProjectReference Include="..\src\OliveGameStudio\OliveGameStudio.csproj" />
    </ItemGroup>
</Project>