<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BattleForce2249.Abstractions\BattleForce2249.Abstractions.csproj" />
      <ProjectReference Include="..\BattleForce2249.Company\BattleForce2249.Company.csproj" />
      <ProjectReference Include="..\BattleForce2249.Game\BattleForce2249.Game.csproj" />
      <ProjectReference Include="..\BattleForce2249.Menu\BattleForce2249.Menu.csproj" />
      <ProjectReference Include="..\OliveGameStudio.UI\OliveGameStudio.UI.csproj" />
      <ProjectReference Include="..\OliveGameStudio\OliveGameStudio.csproj" />
      <ProjectReference Include="..\Pilgrimage\Pilgrimage.csproj" />
    </ItemGroup>

</Project>
