<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OliveGameStudio.UI\OliveGameStudio.UI.csproj" />
      <ProjectReference Include="..\OliveGameStudio\OliveGameStudio.csproj" />
    </ItemGroup>

</Project>
